
version: 2

sources:
  - name: dades_sandbox
    schema: public
    tables:
      - name: energy_budget

  - name: dades_pol
    schema: dbt_pol
    tables:
      - name: average

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: post_fal_model
    description: "A model that uses a output of a fal model"
    columns:
      - name: id
        description: ""
        tests:
          - unique
          - not_null