dbt_dades_sandbox:
  outputs:
    pre_with_fal:
      type: fal
      db_profile: pre # This points to your main adapter
    pre:
      type: postgres
      threads: 1
      host: "{{ env_var('DBHOST') }}"
      port: "{{ env_var('DBPORT') }}"
      user: "{{ env_var('DBUSER') }}"
      password: "{{ env_var('DBPASSWORD') }}"
      dbname: "{{ env_var('DBNAME') }}"
      schema: dbt_pol

  target: pre
